El/us5266 camelize extras
CardTapp/mongoidable pull request #102
Opened 2021-04-22 01:11 UTC by RealNobody

https://rally1.rallydev.com/#/18313249162d/iterationstatus?detail=%2Fuserstory%2F521699462320

2021-04-22 15:04 UTC, jaurand approved these changes
👍

2021-04-22 15:16 UTC, krimsonkla requested changes

2021-04-22 15:16 UTC, krimsonkla commented on lib/mongoidable/casl_hash.rb
> +      self[:conditions] = rule.conditions.transform_keys { |key| key.to_s.camelize(:lower) }
This should be deep_transform_keys

2021-04-26 23:05 UTC, krimsonkla approved these changes

2021-04-26 23:05 UTC, merged